# This script builds the end user installer for Folder Size Calculator
# and then uses the installed to build the portal binaries
# the portal binaries are them compressed and uploaded to the
# github action as output.
name: build-release-binaries
run-name: Release build for ${{ github.event_name }} triggered by ${{ github.triggering_actor }}
concurrency:
  group: release-binaries
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
  workflow_dispatch:
env:
  BUILD_TYPE: Release
  ENDUSER_INSTALLER_FILE_NAME: pdf-combine-setup.msi
jobs:
  prepare-variables:
    runs-on: windows-latest
    outputs:
      build-type: ${{ steps.get-build-type.outputs.build-type }}
      installer-filename: ${{ steps.get-installer-filename.outputs.installer-filename }}
    steps:
      - id: get-build-type
        shell: powershell
        run: echo "build-type=${{ env.BUILD_TYPE }}" >> $env:GITHUB_OUTPUT
      - id: get-installer-filename
        shell: powershell
        run: echo "installer-filename=${{ env.ENDUSER_INSTALLER_FILE_NAME }}" >> $env:GITHUB_OUTPUT

  prepare-environment:
    needs: prepare-variables
    uses: ./.github/workflows/job-prepare-environment.yml

  build-user-installer:
    uses: ./.github/workflows/job-build-user-installer.yml
    needs: [prepare-variables, prepare-environment]
    with:
      build-type: ${{ needs.prepare-variables.outputs.build-type }}
      installer-filename: ${{ needs.prepare-variables.outputs.installer-filename }}
